<style scoped>
    .a{
        color:red;
        .b,.c{
            color:yellow;
        }
        .b:after,.c:after{
            color:blue;
        }
        .d{
            background:url("images/a.png");
        }
    }
</style>
<template>
    <div>
        <a-header></a-header>
        <a-footer></a-footer>
    </div>
</template>
<script>
    export default {
        data:function(){
            return{
            }
        },
        components:{
            "a-header":require("./header"),
            "a-footer":require("./footer")
        }
    };
</script>